version: '3'

services:
  releaser:
    container_name: releaser
    network_mode: "host"
    ipc: "host"
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ./:/app
      - ~/.gitconfig:/etc/gitconfig
      - ~/.ssh:/root/.ssh
