[version]
channel = "Final"
major = 7
minor = 0
patch = 0
revision = 0

[[references]]
file_name = "test_files/__init__.py"
output_type = "Tuple"
variable = "VERSION"

[[references]]
file_name = "test_files/__init__.py"
output_type = "String"
variable = "__version__"

[[references]]
file_name = "test_files/Cargo.toml"
output_type = "String"
variable = "version"

[[references]]
file_name = "test_files/package.json"
output_type = "String"
variable = "version"

[[references]]
file_name = "test_files/test.txt"
output_type = "String"
variable = "version"

[[references]]
file_name = "Cargo.toml"
output_type = "String"
variable = "version"

[settings]
git_url_prefix = "https://github.com/ginger-society/ginger-releaser/commit/"
