[version]
channel = "Final"
major = 4
minor = 2
patch = 2
revision = 2

[[references]]
file_name = "test_files/__init__.py"
output_type = "Tuple"
variable = "VERSION"

[[references]]
file_name = "test_files/__init__.py"
output_type = "String"
variable = "__version__"

[[references]]
file_name = "test_files/Cargo.toml"
variable = "version"

[[references]]
file_name = "test_files/package.json"
variable = "version"
