lang = "Rust"
organization_id = "ginger-society"
dir = "."

[services."@ginger-society/MetadataService"]
stage_k8 = "http://metadata-service-api-service/metadata"
stage = "https://api-staging.gingersociety.org/metadata"
dev = "http://localhost:8081/metadata"

[portals_refs]
